### ISSUE TITLE
Error in upgrade.yml Playbook: Unsupported Parameter for stat Module

### ISSUE THREAD

**Issue by MinerAle00** [geerlingguy/pi-cluster#16]
Hi Jeff,

I encountered an issue while trying to use the upgrade.yml playbook on a Raspberry Pi 5 (8GB) running Raspberry Pi OS Lite 64-bit. The error message I received is as follows:

`
fatal: [pi1.local]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (stat) module: get_md5. Supported parameters include: checksum_algorithm, follow, get_attributes, get_checksum, get_mime, path (attr, attributes, checksum, checksum_algo, dest, mime, mime-type, mime_type, name)."}
`

Steps to Reproduce:

	1.	Run the upgrade.yml playbook.
	2.	Observe the error message related to the stat module.

**Suggested Fix**:
To resolve this issue, simply remove the get_md5: no parameter and replace it with get_checksum: false.

Let me know if you need any further details.

Thanks!

**Comment by geerlingguy** [comment]
@MinerAle00 - Indeed, looks like that code needs updating!
